name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI completed"
      - run: echo "CD completed"